apiVersion: v1
kind: Service
metadata:
  name: zwitscher-consul
  labels:
    zwitscher: consul
spec:
  # Vervollständige die ServiceSpe
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zwitscher-consul
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    # Vervollstaendige das Pod-Template
